package server.idl.departmentServerCorba;


/**
* server/idl/departmentServerCorba/departmentServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server/idl/departmentServerCorba.idl
* Thursday, November 29, 2018 5:08:18 PM EST
*/

abstract public class departmentServerInterfaceHelper
{
  private static String  _id = "IDL:server/idl/departmentServerCorba/departmentServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, server.idl.departmentServerCorba.departmentServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.idl.departmentServerCorba.departmentServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server.idl.departmentServerCorba.departmentServerInterfaceHelper.id (), "departmentServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.idl.departmentServerCorba.departmentServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_departmentServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.idl.departmentServerCorba.departmentServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server.idl.departmentServerCorba.departmentServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.idl.departmentServerCorba.departmentServerInterface)
      return (server.idl.departmentServerCorba.departmentServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.idl.departmentServerCorba._departmentServerInterfaceStub stub = new server.idl.departmentServerCorba._departmentServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static server.idl.departmentServerCorba.departmentServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.idl.departmentServerCorba.departmentServerInterface)
      return (server.idl.departmentServerCorba.departmentServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.idl.departmentServerCorba._departmentServerInterfaceStub stub = new server.idl.departmentServerCorba._departmentServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
