package server.idl.departmentServerCorba;


/**
* server/idl/departmentServerCorba/departmentServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server/idl/departmentServerCorba.idl
* Thursday, November 29, 2018 5:08:18 PM EST
*/

public interface departmentServerInterfaceOperations 
{
  String addCourse (String advisorID, String courseID, String semester, String capacity);
  String removeCourse (String advisorID, String courseID, String semester);
  String listCourseAvailability (String advisorID, String semester);
  String enrolCourse (String studentID, String courseID, String semester);
  String dropCourse (String studentID, String courseID);
  String getClassSchedule (String studentID);
  String swapCourse (String studentID, String newCourseID, String oldCourseID, String semester);
} // interface departmentServerInterfaceOperations
