package server.idl.departmentServerCorba;


/**
* server/idl/departmentServerCorba/departmentServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server/idl/departmentServerCorba.idl
* Thursday, November 29, 2018 5:08:18 PM EST
*/

public interface departmentServerInterface extends departmentServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface departmentServerInterface
